# %% [markdown]
# # Sensitivities as k-space kernels
#
# [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/FiRMLAB-Pisa/mrtoeplitz/blob/main/examples/04-coil_kernels.ipynb)
#
# `CoilKernels`: holding a receive array's sensitivities as small centred
# k-space kernels and expanding one coil at a time — sound exactly when the maps
# are band-limited, which is measured here against three banks from BART.

# %%
try:
    import mrtoeplitz  # noqa: F401
except ImportError:
    import subprocess
    import sys

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "-q",
            "mrtoeplitz[nufft]",
            "matplotlib",
            "finufft",
        ],
        check=True,
    )

# %%
from pathlib import Path
from urllib.request import urlretrieve

import matplotlib.pyplot as plt
import numpy as np
import torch

import mrtoeplitz as mt

# Three sensitivity banks, all produced by BART rather than by hand, and
# regenerated by examples/make_coil_maps.sh:
#
#   simulated : bart coils --H2D8C, its own analytic 8-channel head coil
#   espirit   : bart ecalib, eigenvector-normalised
#   nlinv     : bart nlinv, whose Sobolev weighting is a band limit
local = Path("coil_maps.npz")
if not local.exists():
    urlretrieve(
        "https://raw.githubusercontent.com/FiRMLAB-Pisa/mrtoeplitz/main/"
        "examples/coil_maps.npz",
        local,
    )
loaded = np.load(local)
banks = {
    name: torch.as_tensor(loaded[name]) for name in ("simulated", "espirit", "nlinv")
}
image = torch.as_tensor(loaded["object"]).to(torch.complex64)
n = image.shape[-1]
print({name: tuple(bank.shape) for name, bank in banks.items()})

# %% [markdown]
# ## The kernel is the native form
#
# A sensitivity is smooth. That is not a hope about it — it is why a calibration
# can be solved on a low-resolution ACS region at all, and why NLINV can impose
# a Sobolev weighting and still fit the data. What such a solver produces is a
# small array of k-space coefficients. The dense map is what you get by
# zero-padding that array to the image grid and transforming it.
#
# So the map is the derived object, and forming it is a choice: at 320 cubed
# with 48 channels it costs 12.6 GB, which on most cards *is* the
# reconstruction. `CoilKernels` holds the coefficients instead and defers the
# padding to whichever coils a call actually asks for — which a SENSE normal
# already reads one batch at a time.
#
# Nothing is approximated by this. There is no truncation error to weigh,
# because nothing has been truncated.

# %%
# What a calibration actually solves for. NLINV's Sobolev weighting is a band
# limit, so its unknown *is* a small set of k-space coefficients; the dense map
# is that array zero-padded to the image grid and transformed. Here the
# coefficients are recovered from BART's maps, because its CLI hands back the
# padded form -- in a pipeline they come straight off the solver and the map is
# never formed at all.
coefficients = np.fft.fftshift(
    np.fft.fftn(np.fft.ifftshift(banks["nlinv"].numpy(), axes=(-2, -1)), axes=(-2, -1)),
    axes=(-2, -1),
)
side = 12
centre = n // 2
calibration = torch.as_tensor(
    coefficients[
        :,
        centre - side // 2 : centre + side // 2,
        centre - side // 2 : centre + side // 2,
    ].astype(np.complex64)
)
print(f"the calibration's unknown: {tuple(calibration.shape)}")

# Held as it came. No truncation decision arises, because nothing was
# truncated: the padding is simply deferred.
coil_kernels = mt.CoilKernels(calibration, (n, n))
print(coil_kernels)
print(
    f"{coil_kernels.storage_nbytes / 2**10:.1f} KiB held against "
    f"{coil_kernels.dense_nbytes / 2**10:.0f} KiB of maps"
)

# %% [markdown]
# ## In the normal operator
#
# `apply_sense` takes either a tensor or a `CoilKernels`, and nothing else in a
# solve changes.

# %%
angles = np.linspace(0, np.pi, 96, endpoint=False)
radius = np.linspace(-0.5, 0.5, 192, endpoint=False)
trajectory = np.stack(
    [np.outer(np.cos(angles), radius), np.outer(np.sin(angles), radius)], axis=-1
).astype(np.float32)
density = np.linalg.norm(trajectory, axis=-1).astype(np.float32)
kernel = mt.scalar_kernel(trajectory, (n, n), density=density)

through_maps = mt.apply_sense(kernel, image[None, None], banks["nlinv"])
through_kernels = mt.apply_sense(kernel, image[None, None], coil_kernels)
agreement = float((through_maps - through_kernels).norm() / through_maps.norm())
print(f"SENSE normal through maps and through coil kernels agree to {agreement:.1e}")

# %% [markdown]
# ## If you were handed dense maps instead
#
# Sometimes the coefficients are gone and only the maps remain. Then the
# question is whether the bank can be reduced to a kernel after the fact, and
# that is a measurement — `tolerance` finds the smallest kernel that holds the
# bank to it, reading the error off the spectrum by Parseval rather than
# expanding a candidate.
#
# The three banks below say how far that gets, and it is a good illustration of
# what breaks smoothness: not the physics, but what is done to a map after it is
# estimated.

# %%
sides = (4, 8, 12, 16, 24, 32, 48, 64)
errors = {
    name: [
        float(mt.CoilKernels.from_maps(bank, (k, k)).truncation_error(bank))
        for k in sides
    ]
    for name, bank in banks.items()
}

print(f"{'kernel side':>12}" + "".join(f"{name:>12}" for name in banks))
for index, k in enumerate(sides):
    print(f"{k:>12}" + "".join(f"{errors[name][index]:>12.1e}" for name in banks))

# %%
fig, axes = plt.subplots(1, 4, figsize=(13, 3.2))
for axis, (name, bank) in zip(axes[:3], banks.items(), strict=True):
    axis.imshow(np.abs(bank[0].numpy()), cmap="viridis")
    axis.set_title(f"{name}, coil 0")
    axis.set_xticks([])
    axis.set_yticks([])

for name in banks:
    axes[3].semilogy(sides, errors[name], "o-", markersize=3, label=name)
axes[3].set_title("truncation error")
axes[3].set_xlabel("kernel side")
axes[3].legend(fontsize=8)
fig.tight_layout()

# %%
# Written only when the notebook runs inside a clone, and it is what the
# README shows -- so the figure in the README is always this cell's output.
figures = Path("figures")
if figures.is_dir():
    fig.savefig(figures / "coil_kernels.png", dpi=110, bbox_inches="tight")

# %%
# Asking for a tolerance rather than a size: the kernel is measured from the
# spectrum by Parseval, which costs one transform however many sizes it
# considers -- and a bank with no such kernel is refused rather than quietly
# truncated.
for name, bank in banks.items():
    try:
        chosen = mt.CoilKernels.from_maps(bank, tolerance=1e-3)
        print(
            f"{name:>10}: K={chosen.kernel_shape[0]:3d}, "
            f"{chosen.compression_ratio:5.0f}x smaller, "
            f"error {chosen.truncation_error(bank):.1e}"
        )
    except ValueError as refusal:
        print(f"{name:>10}: refused -- {str(refusal).split(';')[1].strip()}")


# %% [markdown]
# NLINV's maps reduce almost to nothing, which is expected: they were a
# kernel to begin with. ESPIRiT's barely reduce — the `|m| = 1` eigenvector
# normalisation puts a hard edge in the image, and a hard edge has broad k-space
# support, so what is lost is the normalisation's doing rather than the
# sensitivity's. For ESPIRiT the answer is the same as for NLINV: keep the
# calibration kernels and never form the map.
#
# A simulated array is refused outright. Its maps are an analytic field
# evaluated on the grid rather than anything a calibration produced, and a field
# from a conductor decays as a power law.


# %%
def spectrum(bank):
    axes_ = (-2, -1)
    return np.abs(
        np.fft.fftshift(
            np.fft.fftn(np.fft.ifftshift(bank[0].numpy(), axes=axes_), axes=axes_),
            axes=axes_,
        )
    )


fig, axes = plt.subplots(1, 2, figsize=(9.5, 3.4))
middle = n // 2
for name, bank in banks.items():
    profile = spectrum(bank)[middle]
    axes[0].semilogy(np.arange(n) - middle, profile / profile.max(), label=name)
axes[0].set_xlim(-48, 48)
axes[0].set_ylim(1e-9, 2)
axes[0].set_title("k-space of one map")
axes[0].set_xlabel("k")
axes[0].legend(fontsize=8)

for name, bank in banks.items():
    power = spectrum(bank) ** 2
    kept = [
        power[
            middle - k // 2 : middle - k // 2 + k, middle - k // 2 : middle - k // 2 + k
        ].sum()
        / power.sum()
        for k in sides
    ]
    axes[1].semilogy(sides, 1.0 - np.array(kept), "o-", markersize=3, label=name)
axes[1].set_title("energy left outside the kernel")
axes[1].set_xlabel("kernel side")
axes[1].legend(fontsize=8)
fig.tight_layout()

# %% [markdown]
# ## Where it matters
#
# The kernel is set by how smooth the sensitivity is, not by the image, so the
# saving grows with the volume.

# %%
print(f"{'grid':>18}  {'maps':>10}  {'coil kernels':>13}   ratio")
for shape, coils in (((128, 128), 8), ((256, 256, 256), 32), ((320, 320, 320), 48)):
    dense = coils * int(np.prod(shape)) * 8
    kept = coils * side ** len(shape) * 8
    label = "x".join(str(s) for s in shape) + f" x {coils}"
    print(
        f"{label:>18}  {dense / 2**30:8.2f} GB  {kept / 2**20:9.2f} MB  "
        f"{dense / kept:6.0f}x"
    )
